### ISSUE TITLE
Clang check in configure script error

### ISSUE THREAD

**Issue by sknigh** [sstsimulator/sst-macro#347]
@jjwilke 

configure cannot correctly find clang when unless explicitly specified, errors without aborting. The build will generate a linker error. 

```
../configure --with-clang

...

checking clang/AST/AST.h usability... yes
checking clang/AST/AST.h presence... yes
checking for clang/AST/AST.h... yes
checking Checking for offsetof macro definition... "__builtin_offsetof"
../configure: line 23661: yes/bin/llvm-config: No such file or directory
../configure: line 23662: yes/bin/llvm-config: No such file or directory
Traceback (most recent call last):
  File "../bin/config_tools/get_clang_includes", line 18, in <module>
    lines = regexp.search(vOutput).groups()[0].strip().splitlines()
AttributeError: 'NoneType' object has no attribute 'groups'
Traceback (most recent call last):
  File "../bin/config_tools/get_clang_includes", line 18, in <module>
    lines = regexp.search(vOutput).groups()[0].strip().splitlines()
AttributeError: 'NoneType' object has no attribute 'groups'
checking that generated files are newer than configure... done
configure: creating ./config.status
```

The clang presence check passes, but the path defaults to the --with-clang flag's default value of 'yes', creating an incorrect path for the config script tool.

If clang is in the path, I've successfully used this as a workaround.
``` bash
--with-clang=$(dirname $(dirname $(which clang)))
```

**Comment by jjwilke** [comment]
Yes, some new logic got added that was erroneously assuming $clang was set to an actual path. I recommend that we just disallow `--with-clang` without arguments and require `--with-clang` provide a path.
